import product1 from "../../assets/product1.png";
import product2 from "../../assets/product2.png";
import product3 from "../../assets/product3.png";
import product4 from "../../assets/product4.png";

export const ItensData = [
  {
    image: <img src={product1} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$199,00",
    oudPrice: "",
    portionPrice: "ou 6x de R$49,90",
  },
  {
    image: <img src={product2} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$119,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$29,90",
  },
  {
    image: <img src={product3} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "R$149,90",
    portionPrice: "ou 6x de R$22,70",
  },
  {
    image: <img src={product4} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$23,31",
  },
  {
    image: <img src={product1} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$199,00",
    oudPrice: "",
    portionPrice: "ou 6x de R$49,90",
  },
  {
    image: <img src={product2} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$119,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$29,90",
  },
  {
    image: <img src={product3} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "R$149,90",
    portionPrice: "ou 6x de R$22,70",
  },
  {
    image: <img src={product4} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$23,31",
  },
  {
    image: <img src={product1} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$199,00",
    oudPrice: "",
    portionPrice: "ou 6x de R$49,90",
  },
  {
    image: <img src={product2} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$119,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$29,90",
  },
  {
    image: <img src={product3} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "R$149,90",
    portionPrice: "ou 6x de R$22,70",
  },
  {
    image: <img src={product4} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$23,31",
  },
  {
    image: <img src={product1} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$199,00",
    oudPrice: "",
    portionPrice: "ou 6x de R$49,90",
  },
  {
    image: <img src={product2} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$119,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$29,90",
  },
  {
    image: <img src={product3} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "R$149,90",
    portionPrice: "ou 6x de R$22,70",
  },
  {
    image: <img src={product4} alt="" />,
    title: "GÔNDOLA",
    subTitle: "XYZ",
    price: "R$139,90",
    oudPrice: "",
    portionPrice: "ou 6x de R$23,31",
  },
];
